management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

spring:
  cloud:
    stream:
      default-binder: rabbit1
      bindings:
        input:
          group: ${spring.application.name}
          destination: ai-app-default
          binder: rabbit1
        output:
          destination: ai-app-default
          binder: rabbit1

      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${AI_CLOUD_RABBITMQ_HOST:localhost}
                port: ${AI_CLOUD_RABBITMQ_PORT:5672}
                username: ${AI_CLOUD_RABBITMQ_USERNAME:admin}
                password: ${AI_CLOUD_RABBITMQ_PASSWORD:123123}
                virtual-host: ${AI_CLOUD_RABBITMQ_VIRTUAL_HOST:demo}